[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"
nixpacksConfig = "nixpacks.toml"

[build.env]
NIXPACKS_NO_CACHE = "true"

[start]
command = "npm start"

[variables]
NODE_ENV = "production"